version: "3.9"
services:
  agent:
    user: "${UID}"
    build: .
    # image: carloscdias/data_gathering
    container_name: data_gathering-container
    env_file:
      - data_gathering_agent.env
    volumes:
      - data_gathering_volume:/data
  wptagent:
    image: webpagetest/agent
    container_name: wpa_agent-container
    env_file:
      - wpa_agent.env
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: data_gathering-container
volumes:
  data_gathering_volume:  

