version: "3.9"
services:
  broker:
    image: rabbitmq:3.12-management
    hostname: rabbit-server
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "8080:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
volumes:
  rabbitmq:
