version: "3.9"
services:
  broker:
    image: rabbitmq:3.12-management
    hostname: rabbit-server
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  flower:
    image: mher/flower
    ports:
      - "5555:5555"
    command: celery --broker=amqp://guest:guest@broker:5672// flower
    depends_on:
      - broker
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - flower
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
     - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
volumes:
  rabbitmq:
  grafana-storage:
